# Generated by Django 3.1.4 on 2021-01-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('idcode', models.CharField(blank=True, default='', max_length=100)),
                ('picture', models.URLField(blank=True, default='', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('team', models.CharField(blank=True, default='', max_length=100)),
                ('races', models.TextField(default='')),
            ],
            options={
                'unique_together': {('id', 'races')},
            },
        ),
    ]
