# Generated by Django 3.1.4 on 2021-01-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedata', '0002_auto_20210104_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='total_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
