# Generated by Django 3.1.4 on 2021-01-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racedata', '0003_pilot_total_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilot',
            options={'ordering': ['-total_pts']},
        ),
        migrations.AlterField(
            model_name='pilot',
            name='idcode',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='races',
            field=models.TextField(default='', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='pilot',
            unique_together={('id',)},
        ),
    ]
